- hosts: bastion
  remote_user: ubuntu
  become: yes         
  roles:
    - docker
    - kubectl
    - jenkins
  

# - hosts: private
#   remote_user: ubuntu
#   become: yes 
#   roles: 
#     # - jenkins
#     - docker
    