- name: update
  ansible.builtin.apt:
    update_cache: yes

- name: Install apache   
  ansible.builtin.apt:
    name: apache2
    state: present
  notify: update

- name: start and enable apache2
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: yes
